// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfa1QTZtRIvp6qB46UNZwT_ZpRLcFDRKo',
    appId: '1:792157443286:web:edf4f730f632ca0cfce577',
    messagingSenderId: '792157443286',
    projectId: 'flipifly-9df88',
    authDomain: 'flipifly-9df88.firebaseapp.com',
    storageBucket: 'flipifly-9df88.firebasestorage.app',
    measurementId: 'G-SDVB99M3GF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrE89ML2eZTUZUAIIacFOzSmI6Kq0fMiU',
    appId: '1:792157443286:android:c04ceb6b9541f008fce577',
    messagingSenderId: '792157443286',
    projectId: 'flipifly-9df88',
    storageBucket: 'flipifly-9df88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9rsFMtivPP5yYQ4W1s2MQFAFLCKPIOtY',
    appId: '1:792157443286:ios:d2d292b5c1e4cea5fce577',
    messagingSenderId: '792157443286',
    projectId: 'flipifly-9df88',
    storageBucket: 'flipifly-9df88.firebasestorage.app',
    iosBundleId: 'com.example.flipifly',
  );
}
