// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz3H-rpXB-YdODRqJV_Ny10ufpuSlVOkM',
    appId: '1:792157443286:web:2f0e43922a58092cfce577',
    messagingSenderId: '792157443286',
    projectId: 'flipifly-9df88',
    authDomain: 'flipifly-9df88.firebaseapp.com',
    storageBucket: 'flipifly-9df88.firebasestorage.app',
    measurementId: 'G-WHP1H4V6VJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrE89ML2eZTUZUAIIacFOzSmI6Kq0fMiU',
    appId: '1:792157443286:android:d7e2fcd5a2f20551fce577',
    messagingSenderId: '792157443286',
    projectId: 'flipifly-9df88',
    storageBucket: 'flipifly-9df88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9rsFMtivPP5yYQ4W1s2MQFAFLCKPIOtY',
    appId: '1:792157443286:ios:14fe9cf9369598b7fce577',
    messagingSenderId: '792157443286',
    projectId: 'flipifly-9df88',
    storageBucket: 'flipifly-9df88.firebasestorage.app',
    androidClientId: '792157443286-3u7cn30stqis39qnm33bho99vfram2ud.apps.googleusercontent.com',
    iosClientId: '792157443286-d4i1imf03lj1suug4obec24j1hkruav3.apps.googleusercontent.com',
    iosBundleId: 'com.example.webkit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9rsFMtivPP5yYQ4W1s2MQFAFLCKPIOtY',
    appId: '1:792157443286:ios:14fe9cf9369598b7fce577',
    messagingSenderId: '792157443286',
    projectId: 'flipifly-9df88',
    storageBucket: 'flipifly-9df88.firebasestorage.app',
    androidClientId: '792157443286-3u7cn30stqis39qnm33bho99vfram2ud.apps.googleusercontent.com',
    iosClientId: '792157443286-d4i1imf03lj1suug4obec24j1hkruav3.apps.googleusercontent.com',
    iosBundleId: 'com.example.webkit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz3H-rpXB-YdODRqJV_Ny10ufpuSlVOkM',
    appId: '1:792157443286:web:e8a6962123509873fce577',
    messagingSenderId: '792157443286',
    projectId: 'flipifly-9df88',
    authDomain: 'flipifly-9df88.firebaseapp.com',
    storageBucket: 'flipifly-9df88.firebasestorage.app',
    measurementId: 'G-G2QJR87S49',
  );

}